name = "jproject"
main = "worker/index.ts"
compatibility_date = "2026-02-14"

[[d1_databases]]
binding = "DB"
database_name = "guitar_practice_db"
database_id = "30381490-d023-4667-af85-8badc2b47cb9"
migrations_dir = "db/migrations"
